name: "Spell"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./.nvmrc
      - uses: reviewdog/action-setup@v1
      - run: npm install
      - name: Spell check
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run spellcheck | reviewdog -efm="%f:%l:%c - %m" -reporter=github-pr-review -filter-mode=nofilter -fail-on-error=true
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Spell check
        if: ${{ github.event_name != 'pull_request' }}
        run: npm run spellcheck
