name: "Test & Publish"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "main"
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
      - run: yarn install
      - run: xvfb-run -a yarn test
        if: runner.os == 'Linux'
      - run: yarn test
        if: runner.os != 'Linux'
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        run: yarn vscode:publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Create package
        run: yarn vsce package
      - name: Release
        if: success() && startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v1
        with:
          files: wave-dash-unify-*.vsix
